.TH HUAYRA-RECOVERY 1 2016-04-06 huayra-recovery
.SH NAME
huayra-recovery \- scripts para el sistema de recuperación

.SH SYNOPSIS
.B huayra-recovery

.SH DESCRIPTION



.SH VARIABLES

Estas variables se usan basicamente en modo de desarrollo

ADV_MENU archivo del menu avanzado (por defecto /usr/share/huayra/recovery/huarya-recovery-adv) 

CONECTADO si se fuerza a 1 se pasa de alto la comprobacion de conexion a la red electrica

DIALOGRC archivo de configuracion de dialog (por defecto (/etc/huayra/dialogrc)

See http://github.com/HuayarLinux/huayra-recovery
