.TH HUAYRA-RECOVERY 1 2016-04-06 huayra-recovery
.SH NAME
huayra-recovery \- scripts para el sistema de recuperación

.SH SYNOPSIS
.B [OPCION1=VALOR1] [OPCION2=VALOR2] huayra-recovery

.SH DESCRIPTION

Esta herramienta se utiliza para el sistema de recuperación.

.SH ENVIRONMENT

Estas variables se usan básicamente en modo de desarrollo

.B ADV_MENU 
Si su valor es 1, se muestra el menu avanzado (deshabilitado por defecto)

.B ADV_MENU_FILE 
Archivo del menu avanzado (por defecto /usr/share/huayra/recovery/huarya-recovery-adv)

.B CONECTADO
Si se fuerza a 1 se pasa de alto la comprobación de conexión a la red eléctrica

.B DIALOGRC 
Archivo de configuración de dialog (por defecto (/etc/huayra/dialogrc)

.B DEBUG
Si se fuerza a 1 no se realizan las operaciones y se muestra un diálogo con las acciones


Ejemplo: 

.B DEBUG=1 ADV_MENU=1 huayra-recovery 

.SH FILES

/etc/default/huayra-recovery

Estas variables se pueden utilizar, creando el archivo /etc/default/huayra-recovery y
agregándolas al mismo.

See http://github.com/HuayarLinux/huayra-recovery
